title: BioShell
baseurl: "/BioShell-User-Guide"
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

#topnav_title: BioShell
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "A guide to accessing and using BioShell, a preconfigured cloud bioinformatics environment on NCI Nirin and ARDC Nectar Research Cloud."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.5.0

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/navbar_logo.png

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
