title: BioShell
baseurl: "/BioShell-User-Guide"
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: '<img src="/BioShell-User-Guide/assets/img/Australian-Biocommons-Logo-Tagline-Community-RGB.png" alt="Australian BioCommons" style="height:40px; margin-left:12px;">'
# Rendered as raw HTML next to the brand_logo in the top navigation bar

description: "A guide to accessing and using BioShell, a preconfigured cloud bioinformatics environment on NCI Nirin and ARDC Nectar Research Cloud."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.5.0

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/BioShell_logo_with_name.png

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
